owner: Zan1456
repo: uptime

sites:
  - name: Zan1456 weboldala
    url: https://zan1456.hu

status-website:
  baseUrl: /uptime
  logoUrl: https://i.imgur.com/FGNFcN2.png
  name: reFilc állapot
  introTitle: "Itt találod a **Zan1456** által működtetett oldalaknak az állapotát"
  introMessage: Probléma esetén kérlek nyiss egy Issue-t a Github-on.
  navbar:
    - title: Állapot
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
