owner: Zan1456
repo: uptime

sites:
  - name: reFilc
    url: https://refilc.hu

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: reFilc állapot
  introTitle: "Itt találod a **reFilc** által működtetett oldalaknak az állapotát"
  introMessage: Probléma esetén kérlek nyiss egy Issue-t a Github-on.
  navbar:
    - title: Állapot
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
