owner: Zan1456
repo: uptime

sites:
  - name: Zan1456 weboldala
    url: https://zan1456.dev
  - name: Firka
    url: https://firka.app

status-website:
  baseUrl: /uptime
  logoUrl: https://i.imgur.com/FGNFcN2.png
  name: Weboldalaim elérhetősége
  introTitle: "Itt találod a **Zan1456** által működtetett oldalaknak az állapotát"
  introMessage: Probléma esetén kérlek nyiss egy hibajelentést Githubon.
  navbar:
    - title: Állapot
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
